// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0skvqA2l4QhCl76z41nw0nbPlL2JZS40',
    appId: '1:674189591699:web:625c1151dbe15d87a3f966',
    messagingSenderId: '674189591699',
    projectId: 'test-project-2404c',
    authDomain: 'test-project-2404c.firebaseapp.com',
    storageBucket: 'test-project-2404c.appspot.com',
    measurementId: 'G-QE2CMFKLRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnd6sjYafKiTqsLPrfYiupNiSM73uEuU',
    appId: '1:674189591699:android:2342b32bd7277fe7a3f966',
    messagingSenderId: '674189591699',
    projectId: 'test-project-2404c',
    storageBucket: 'test-project-2404c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lTLzA5a92WkpjuGvTwX_bacwDn3Tr5I',
    appId: '1:674189591699:ios:fd7f9e07bc2dac2aa3f966',
    messagingSenderId: '674189591699',
    projectId: 'test-project-2404c',
    storageBucket: 'test-project-2404c.appspot.com',
    iosBundleId: 'com.example.blocArchitectureFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6lTLzA5a92WkpjuGvTwX_bacwDn3Tr5I',
    appId: '1:674189591699:ios:fd7f9e07bc2dac2aa3f966',
    messagingSenderId: '674189591699',
    projectId: 'test-project-2404c',
    storageBucket: 'test-project-2404c.appspot.com',
    iosBundleId: 'com.example.blocArchitectureFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0skvqA2l4QhCl76z41nw0nbPlL2JZS40',
    appId: '1:674189591699:web:c57db8700ffba851a3f966',
    messagingSenderId: '674189591699',
    projectId: 'test-project-2404c',
    authDomain: 'test-project-2404c.firebaseapp.com',
    storageBucket: 'test-project-2404c.appspot.com',
    measurementId: 'G-MXVEHCGVQT',
  );
}
